# CHIP-8 Emulator CMake configuration
# This file includes all CHIP-8 instructions
# This file is autogenerated by a python script
# Do not modify this file manually

## Define the path to the library
set(LIB_PATH libraries/chip8++)

include_directories(${CMAKE_SOURCE_DIR}/${LIB_PATH})

set(LIB_PATH_FILES
	${LIB_PATH}/system/memory.hpp 
	${LIB_PATH}/system/timers.hpp 
	${LIB_PATH}/system/keypad.hpp 
	${LIB_PATH}/system/display.hpp 
	${LIB_PATH}/system/quirks.hpp
	${LIB_PATH}/system/cpu.hpp ${LIB_PATH}/system/cpu.cpp
	${LIB_PATH}/Instructions/Instruction.hpp
	${LIB_PATH}/Instructions/Illegal.hpp
	${LIB_PATH}/Instructions/InstructionList.hpp
	${LIB_PATH}/Instructions/00E0.hpp
	${LIB_PATH}/Instructions/00EE.hpp
	${LIB_PATH}/Instructions/1NNN.hpp
	${LIB_PATH}/Instructions/2NNN.hpp
	${LIB_PATH}/Instructions/3XKK.hpp
	${LIB_PATH}/Instructions/4XKK.hpp
	${LIB_PATH}/Instructions/5XY0.hpp
	${LIB_PATH}/Instructions/6XKK.hpp
	${LIB_PATH}/Instructions/7XKK.hpp
	${LIB_PATH}/Instructions/8XY0.hpp
	${LIB_PATH}/Instructions/8XY1.hpp
	${LIB_PATH}/Instructions/8XY2.hpp
	${LIB_PATH}/Instructions/8XY3.hpp
	${LIB_PATH}/Instructions/8XY4.hpp
	${LIB_PATH}/Instructions/8XY5.hpp
	${LIB_PATH}/Instructions/8XY6.hpp
	${LIB_PATH}/Instructions/8XY7.hpp
	${LIB_PATH}/Instructions/8XYE.hpp
	${LIB_PATH}/Instructions/9XY0.hpp
	${LIB_PATH}/Instructions/ANNN.hpp
	${LIB_PATH}/Instructions/BNNN.hpp
	${LIB_PATH}/Instructions/CXKK.hpp
	${LIB_PATH}/Instructions/DXYN.hpp
	${LIB_PATH}/Instructions/EX9E.hpp
	${LIB_PATH}/Instructions/EXA1.hpp
	${LIB_PATH}/Instructions/FX07.hpp
	${LIB_PATH}/Instructions/FX0A.hpp
	${LIB_PATH}/Instructions/FX15.hpp
	${LIB_PATH}/Instructions/FX18.hpp
	${LIB_PATH}/Instructions/FX1E.hpp
	${LIB_PATH}/Instructions/FX29.hpp
	${LIB_PATH}/Instructions/FX33.hpp
	${LIB_PATH}/Instructions/FX55.hpp
	${LIB_PATH}/Instructions/FX65.hpp
)
add_library(chip8lib ${LIB_PATH_FILES})

